spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${PG_HOST}:${PG_PORT}/demo_data_source
    username: ${PG_USER}
    password: ${PG_PASSWORD}

#  jpa:
#    hibernate:
#      ddl-auto: update
server:
  port: 8081
